class cfgFunctions {
	class fen {
		class functions {
			file="fen_A3\addons\fen_functions\functions";
			class airAssault;
			class aiSpotter;
			class airResupply;
			class airResupply_drop;
			class artilleryFX;
			class artilleryLine;
			class bldPatrol;
			class boobyTrapVeh;
			class civilianArea;
			class civTalk_addAction;
			class civTalk_addConversation;
			class civTalk_speak;
			class cntOwnedUnts;
			class covert;
			class covert_debug;
			class covert_initPlayer;
			class covert_onPlayerKilled;
			class covert_onPlayerRespawn;
			class counterAttack;
			class dicker;
			class dltGroup;
			class flares;
			class fndClearLoc;
            class forwardObs;
			class grpDefend;
			class grpStaticPos;
			class grpSurrender;
			class hiddenEnemy;
			class iedMan;
			class iedObject;
			class iedPP;
			class intel_addAction;
			class intel_addIntel;
			class intel_gather;
			class nearTargets;
			class playersInTrigger;
			class releaseSentries;
			class retreatGroup;
			class rollingBarrage;
			class rtnBuildingPos;
			class say3d;
			class scrambleCrew;
			class sideChatGbl;
			class spawnGroup;
			class spawnSentries;
			class spawnVehicle;
			class suicideBomber;
			class vehAssault;
		};
	};
};